export const FETCH_MOVIE_DETAIL_CL_REQUEST = "FETCH_MOVIE_DETAIL_CL_REQUEST";
export const FETCH_MOVIE_DETAIL_CL_SUCCESS = "FETCH_MOVIE_DETAIL_CL_SUCCESS";
export const FETCH_MOVIE_DETAIL_CL_FAIL = "FETCH_MOVIE_DETAIL_CL_FAIL";
